name: Linter

on:
  pull_request:
    paths:
      - '**.php'

jobs:
  pint:
    name: pint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Pint
        uses: aglipanci/laravel-pint-action@2.3.0
        with:
          preset: laravel
